### ISSUE TITLE
Question: using cbird appimage in docker container

### ISSUE THREAD

**Issue by phirestalker** [scrubbbbs/cbird#23]
I was wondering if you have ever successfully ran cbird inside a docker container. When I try (even with --privileged) it says operation not supported (or allowed I forget) when trying to mount using /dev/fuse. I have shared the device file into the container, so I am not sure what else to try.

I don't expect you to solve this for me as it is out of scope. I am just hoping you might have done it before while testing your program.

Thanks.

**Comment by scrubbbbs** [comment]
I haven't played with docker much. If the appimage doesn't work, there's always compiling...

**Comment by phirestalker** [comment]
Ya, I think I will bake the compiling into the Docker image to make it easier. I was just hoping for the easy way out.
