### ISSUE TITLE
Indexer: segv on corrupt / partial corrupt video

### ISSUE THREAD

**Issue by chapmanjacobd** [scrubbbbs/cbird#8]
Sorry for opening so many tickets. I haven't encountered anything yet which has blocked me from being productive with the tool. But I did encounter a strange edge case. The error is reproducible with the specific file.

[segv_partially_corrupt_video.txt](https://github.com/scrubbbbs/cbird/files/12164589/segv_partially_corrupt_video.txt)

Maybe a solution could be to keep track of number of errors and skip indexing a file after 3 or 20 errors or something like that

**Comment by scrubbbbs** [comment]
I'd like to understand the source of the segfault, there could be a better fix besides error threshold.

Can you run this by gdb or upload the file somewhere?

`gdb --args cbird ...`

Then type "run" at the prompt, and "backtrace" at the segfault.

**Comment by chapmanjacobd** [comment]
oops... I already [redownloaded](https://ia601007.us.archive.org/12/items/BBCHorizonCollection512Episodes/BBC%20Horizon%20-%20s0000e45%20-%20Doctors%20in%20the%20Death%20Zone%201of2%20Special.avi) it. I replaced the corrupt video with the redownloaded copy and I don't get the error any more :/

I will close this and reopen with a backtrace if I encounter the error again with a different file
