### ISSUE TITLE
Issues with GPU option.

### ISSUE THREAD

**Issue by tehMArs** [scrubbbbs/cbird#9]
@scrubbbbs 
My hardware: 
AMD Ryzen 5 3600
NVIDIA GeForce RTX 4070 Ti SUPER / before GTX 1660S
16 GB ram
Nvme / HDD`s
antivirus is OFF

For now **-i.gpu** is for no use, i cannot complete the whole scan of data, tried limit threads cpu/gpu usage but didnt worked.
without that option is so slow for example scanning takes one day instead of 2 hours. No matter its Nvme or HDD same error appear

Many of them
[C][VideoContext::open{AAAAAAAALASTONEPULPIT/df11123ZD.mp4}] cannot open input -18 "Too many open files"
[W][Scanner::setError{AAAAAAAALASTONEPULPIT/df11123ZD.mp4}] "Y:/AAAAAAAALASTONEPULPIT/df11123ZD.mp4" "format error"
[C][VideoContext::open{AAAAAAAALASTONEPULPIT/df11123ZD.mp4}] cannot open input -18 "Too many open files"
[W][Scanner::setError{AAAAAAAALASTONEPULPIT/df11123ZD.mp4}] "Y:/AAAAAAAALASTONEPULPIT/df11123ZD.mp4" "format error"
[C][VideoContext::open{2014h4dds.mp4}] cannot open input -18 "Too many open files"
[W][Scanner::setError{2014h4dds.mp4}] "Y:/2014h4dds.mp4" "format error"
[C][VideoContext::open{FTB-noHW.mp4}] cannot open input -18 "Too many open files"
[W][Scanner::setError{FTB-noHW.mp4}] "Y:/FTB-noHW.mp4" "format error"

so on so on  "Too many open files" 

finally gave me this

[F][VideoIndex::save{Y:/_index/video/457.vdx}] failed to open

end of scan.

**Comment by scrubbbbs** [comment]
Duplicate of #11
